stages:
  - test

variables:
  NODE_ENV: "test"

test_job:
  stage: test
  image: node:14
  before_script:
    - npm ci
  script:
    - npm run test
  artifacts:
    paths:
      - coverage/
  except:
    - master
