stages:
  - test

variables:
  NODE_ENV: "test"

test_job:
  stage: test
  image: node:14  
  before_script:
    - apt-get update && apt-get install -y build-essential
    - npm install --global npm@latest  # Actualizar npm a la última versión
    - npm install --legacy-peer-deps  # Instalación de dependencias, evitando problemas con dependencias desactualizadas
    - npm install jest @babel/core @babel/preset-env babel-jest --save-dev  # Instalar Jest y Babel como dependencias de desarrollo
  script:
    - jest tests/FizzBuzz.test.js  # Ejecutar los tests específicos de FizzBuzz