stages:
  - test

test_job:
  stage: test
  image: node:14
  before_script:
    - npm install
    - npm install jest 
    - npm install @babel/core @babel/preset-env @babel/cli jest babel-jest --save-dev

  script:
    - npm run test
